# Generated by Django 3.2 on 2022-11-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_alter_asset_asset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='id_s',
            field=models.IntegerField(default=1),
        ),
    ]
