# Generated by Django 3.2 on 2022-11-06 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_asset_id_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='id_s',
        ),
    ]
